// Created so we have access to it instead of Browser history being generated by BrowserRouter
// BrowserRouter also changes back to Plain Router since we're generating our own history
import { createBrowserHistory } from 'history'; 
export default createBrowserHistory();
